# SPDX-License-Identifier: Apache-2.0

[workspace]
members = ["rasterm-sys", "rasterm"]
resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/rasterm/rasterm"
homepage = "https://github.com/rasterm/rasterm"
rust-version = "1.85"
 
