# SPDX-License-Identifier: Apache-2.0

[package]
name = "rasterm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"
publish = ["crates-io"]
description = "Safe Rust bindings for rasterm terminal graphics"
categories = ["multimedia::images", "rendering"]
keywords = ["terminal", "graphics", "sixel", "rendering"]

[dependencies]
rasterm-sys = { version = "1.2.0", path = "../rasterm-sys" }
