/* SPDX-License-Identifier: Apache-2.0 */

#ifndef RASTERM_DEFAULTS_H
#define RASTERM_DEFAULTS_H

/* cross language defaults. C++, the C ABI initializers, and binding
   conformance tests all derive or validate their values against this table. */

#define RASTERM_DEFAULT_QUALITY 0
#define RASTERM_DEFAULT_USE_ALTERNATE_SCREEN 0
#define RASTERM_DEFAULT_PRESERVE_CURSOR 1
#define RASTERM_DEFAULT_ENABLE_DIRTY_REGIONS 0
#define RASTERM_DEFAULT_REQUIRE_SIXEL_SUPPORT 0
#define RASTERM_DEFAULT_USE_SYNCHRONIZED_OUTPUT 1
#define RASTERM_DEFAULT_MAXIMUM_OUTPUT_BYTES 0ULL
#define RASTERM_DEFAULT_BACKPRESSURE_MILLISECONDS 12.0
#define RASTERM_DEFAULT_CONVERT_TO_SRGB 1
#define RASTERM_DEFAULT_TONE_MAP 3
#define RASTERM_DEFAULT_OUTPUT_PEAK_NITS 203.0f
#define RASTERM_DEFAULT_REALTIME_DITHER 0
#define RASTERM_DEFAULT_ADAPTIVE_PALETTE_LOCK_FRAMES 12
#define RASTERM_DEFAULT_SCENE_CUT_THRESHOLD 0.30f
#define RASTERM_DEFAULT_PERSIST_PALETTE_REGISTERS 1
#define RASTERM_DEFAULT_PALETTE_REFRESH_FRAMES 120
#define RASTERM_DEFAULT_OUTPUT_CHUNK_BYTES (64ULL * 1024ULL)
#define RASTERM_DEFAULT_MAXIMUM_ENCODER_THREADS 0
#define RASTERM_DEFAULT_INDEPENDENT_REGION_QUANTIZATION 1
#define RASTERM_DEFAULT_MAXIMUM_FRAMES_PER_SECOND 0.0
#define RASTERM_DEFAULT_REFERENCE_WHITE_NITS 203.0f
#define RASTERM_DEFAULT_MASTERING_PEAK_NITS 1000.0f

#endif
